name: Build & Publish
on:
  push:
    branches:
      - "upload"

jobs:
  build_on_debian_stretch:
    runs-on: ubuntu-latest
    container:
      image: debian:stretch
    steps:
      - uses: actions/checkout@v3
      - run: bash .github/workflows/scripts/build_deb.sh
      - uses: actions/upload-artifact@v3
        with:
          path: /output/*

  upload_to_repo:
    runs-on: ubuntu-latest
    needs: [build_on_debian_stretch]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          path: ./artifact
      - name: "Upload to repo server..."
        run: bash .github/workflows/scripts/upload_to_repo.sh
        env:
          UPLOAD_TOKEN: ${{ secrets.UPLOAD_TOKEN }}
