name: Build RPM packages
on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:

  build_on_centos6:
    runs-on: ubuntu-latest
    container:
      image: centos:6
    steps:
      - uses: actions/checkout@v3
      - run: bash .github/workflows/build_rpm.sh

  build_on_centos7:
    runs-on: ubuntu-latest
    container:
      image: centos:7
    steps:
      - uses: actions/checkout@v3
      - run: bash .github/workflows/build_rpm.sh

  build_on_centos8:
    runs-on: ubuntu-latest
    container:
      image: centos:8
    steps:
      - uses: actions/checkout@v3
      - run: bash .github/workflows/build_rpm.sh