name: Build DEB packages
on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:

  build_on_ubuntu16:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:16.04
      volumes:
        - ./output:/output
    steps:
      - uses: actions/checkout@v3
      - run: bash .github/workflows/scripts/build_deb.sh
    
  build_on_ubuntu18:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:18.04
      volumes:
        - ./output:/output
    steps:
      - uses: actions/checkout@v3
      - run: bash .github/workflows/scripts/build_deb.sh

  build_on_ubuntu22:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
      volumes:
        - ./output:/output
    steps:
      - uses: actions/checkout@v3
      - run: bash .github/workflows/scripts/build_deb.sh
  
  build_on_centos7:
    runs-on: ubuntu-latest
    container:
      image: centos:7
      volumes:
        - ./output:/output
    steps:
      - uses: actions/checkout@v3
      - run: bash .github/workflows/scripts/build_rpm.sh

  build_on_centos8:
    runs-on: ubuntu-latest
    container:
      image: centos:8
      volumes:
        - ./output:/output
    steps:
      - uses: actions/checkout@v3
      - run: bash .github/workflows/scripts/build_rpm.sh
  
  upload_to_repo:
    runs-on: ubuntu-latest
    needs: [build_on_ubuntu16, build_on_ubuntu18, build_on_ubuntu22, build_on_centos7, build_on_centos8]
    steps:
      - run: bash .github/workflows/scripts/upload_to_repo.sh