name: Build binary packages
on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:

  build_on_ubuntu16:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:16.04
    steps:
      - uses: actions/checkout@v3
      - run: bash .github/workflows/scripts/build_deb.sh
      - uses: actions/upload-artifact@v3
        with:
          path: /output/*
    
  build_on_ubuntu18:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:18.04
    steps:
      - uses: actions/checkout@v3
      - run: bash .github/workflows/scripts/build_deb.sh
      - uses: actions/upload-artifact@v3
        with:
          path: /output/*

  # build_on_ubuntu22:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: ubuntu:22.04
  #   steps:
  #     - uses: actions/checkout@v3
  #     - run: bash .github/workflows/scripts/build_deb.sh
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         path: /output/*
  
  # build_on_centos7:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: centos:7
  #   steps:
  #     - uses: actions/checkout@v3
  #     - run: bash .github/workflows/scripts/build_rpm.sh
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         path: /output/*

  # build_on_centos8:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: centos:8
  #   steps:
  #     - uses: actions/checkout@v3
  #     - run: bash .github/workflows/scripts/build_rpm.sh
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         path: /output/*
  
  upload_to_repo:
    runs-on: ubuntu-latest
    needs: [build_on_ubuntu16, build_on_ubuntu18]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          path: .
      - run: bash .github/workflows/scripts/upload_to_repo.sh