name: Build DEB packages
on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:

  build_on_ubuntu16:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:16.04
    steps:
      - uses: actions/checkout@v3
      - run: bash .github/workflows/build_deb.sh
    
  build_on_ubuntu18:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:18.04
    steps:
      - uses: actions/checkout@v3
      - run: bash .github/workflows/build_deb.sh

  build_on_ubuntu22:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    steps:
      - uses: actions/checkout@v3
      - run: bash .github/workflows/build_deb.sh