name: Build & Publish
on:
  push:
    branches:
      - "main"
    tags:
      - "v*"

jobs:
  build_on_debian_stretch:
    runs-on: ubuntu-latest
    container:
      image: debian:stretch # ubuntu16.04-17.10
    steps:
      - uses: actions/checkout@v3
      - run: bash .github/workflows/scripts/build_deb.sh
      - uses: actions/upload-artifact@v3
        with:
          path: /output/*

  build_on_debian_buster:
    runs-on: ubuntu-latest
    container:
      image: debian:buster # ubuntu18.04-19.10
    steps:
      - uses: actions/checkout@v3
      - run: bash .github/workflows/scripts/build_deb.sh
      - uses: actions/upload-artifact@v3
        with:
          path: /output/*

  build_on_debian_bullseye:
    runs-on: ubuntu-latest
    container:
      image: debian:bullseye # ubuntu20.04-21.10
    steps:
      - uses: actions/checkout@v3
      - run: bash .github/workflows/scripts/build_deb.sh
      - uses: actions/upload-artifact@v3
        with:
          path: /output/*

  build_on_debian_bookworm:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm # ubuntu22.04-ubuntu23.10
    steps:
      - uses: actions/checkout@v3
      - run: bash .github/workflows/scripts/build_deb.sh
      - uses: actions/upload-artifact@v3
        with:
          path: /output/*

  build_on_centos7:
    runs-on: ubuntu-latest
    container:
      image: centos:7
    steps:
      - uses: actions/checkout@v3
      - run: bash .github/workflows/scripts/build_rpm.sh
      - uses: actions/upload-artifact@v3
        with:
          path: /output/*

  build_on_centos8:
    runs-on: ubuntu-latest
    container:
      image: centos:8
    steps:
      - uses: actions/checkout@v3
      - run: bash .github/workflows/scripts/build_rpm.sh
      - uses: actions/upload-artifact@v3
        with:
          path: /output/*

  upload_to_repo:
    runs-on: ubuntu-latest
    needs:
      [
        build_on_debian_stretch,
        build_on_debian_buster,
        build_on_debian_bullseye,
        build_on_debian_bookworm,
        build_on_centos7,
        build_on_centos8,
      ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          path: ./artifact
      - run: bash .github/workflows/scripts/upload_to_repo.sh
