name: Test libssl version
on:
  push:
    branches:
      - "ssl"

jobs:
  build_on_debian_stretch:
    runs-on: ubuntu-latest
    container:
      image: debian:stretch
    steps:
      - uses: actions/checkout@v3
      - run: bash .github/workflows/scripts/get_libssl_info.sh
      - uses: actions/upload-artifact@v3
        with:
          path: /output/*

  build_on_debian_buster:
    runs-on: ubuntu-latest
    container:
      image: debian:buster
    steps:
      - uses: actions/checkout@v3
      - run: bash .github/workflows/scripts/get_libssl_info.sh
      - uses: actions/upload-artifact@v3
        with:
          path: /output/*

  build_on_debian_bullseye:
    runs-on: ubuntu-latest
    container:
      image: debian:bullseye
    steps:
      - uses: actions/checkout@v3
      - run: bash .github/workflows/scripts/get_libssl_info.sh
      - uses: actions/upload-artifact@v3
        with:
          path: /output/*

  build_on_debian_bookworm:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm
    steps:
      - uses: actions/checkout@v3
      - run: bash .github/workflows/scripts/get_libssl_info.sh
      - uses: actions/upload-artifact@v3
        with:
          path: /output/*

  build_on_ubuntu_xenial:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:xenial
    steps:
      - uses: actions/checkout@v3
      - run: bash .github/workflows/scripts/get_libssl_info.sh
      - uses: actions/upload-artifact@v3
        with:
          path: /output/*

  build_on_ubuntu_yakkety:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:yakkety
    steps:
      - uses: actions/checkout@v3
      - run: bash .github/workflows/scripts/get_libssl_info.sh
      - uses: actions/upload-artifact@v3
        with:
          path: /output/*

  build_on_ubuntu_zesty:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:zesty
    steps:
      - uses: actions/checkout@v3
      - run: bash .github/workflows/scripts/get_libssl_info.sh
      - uses: actions/upload-artifact@v3
        with:
          path: /output/*

  build_on_ubuntu_artful:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:artful
    steps:
      - uses: actions/checkout@v3
      - run: bash .github/workflows/scripts/get_libssl_info.sh
      - uses: actions/upload-artifact@v3
        with:
          path: /output/*

  build_on_ubuntu_bionic:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:bionic
    steps:
      - uses: actions/checkout@v3
      - run: bash .github/workflows/scripts/get_libssl_info.sh
      - uses: actions/upload-artifact@v3
        with:
          path: /output/*

  build_on_ubuntu_cosmic:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:cosmic
    steps:
      - uses: actions/checkout@v3
      - run: bash .github/workflows/scripts/get_libssl_info.sh
      - uses: actions/upload-artifact@v3
        with:
          path: /output/*

  build_on_ubuntu_disco:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:disco
    steps:
      - uses: actions/checkout@v3
      - run: bash .github/workflows/scripts/get_libssl_info.sh
      - uses: actions/upload-artifact@v3
        with:
          path: /output/*

  build_on_ubuntu_eoan:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:eoan
    steps:
      - uses: actions/checkout@v3
      - run: bash .github/workflows/scripts/get_libssl_info.sh
      - uses: actions/upload-artifact@v3
        with:
          path: /output/*

  build_on_ubuntu_focal:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:focal
    steps:
      - uses: actions/checkout@v3
      - run: bash .github/workflows/scripts/get_libssl_info.sh
      - uses: actions/upload-artifact@v3
        with:
          path: /output/*

  build_on_ubuntu_groovy:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:groovy
    steps:
      - uses: actions/checkout@v3
      - run: bash .github/workflows/scripts/get_libssl_info.sh
      - uses: actions/upload-artifact@v3
        with:
          path: /output/*

  build_on_ubuntu_hirsute:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:hirsute
    steps:
      - uses: actions/checkout@v3
      - run: bash .github/workflows/scripts/get_libssl_info.sh
      - uses: actions/upload-artifact@v3
        with:
          path: /output/*

  build_on_ubuntu_impish:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:impish
    steps:
      - uses: actions/checkout@v3
      - run: bash .github/workflows/scripts/get_libssl_info.sh
      - uses: actions/upload-artifact@v3
        with:
          path: /output/*

  build_on_ubuntu_jammy:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:jammy
    steps:
      - uses: actions/checkout@v3
      - run: bash .github/workflows/scripts/get_libssl_info.sh
      - uses: actions/upload-artifact@v3
        with:
          path: /output/*

  upload_to_repo:
    runs-on: ubuntu-latest
    needs:
      [
        build_on_debian_stretch,
        build_on_debian_buster,
        build_on_debian_bullseye,
        build_on_debian_bookworm,
        build_on_ubuntu_xenial,
        build_on_ubuntu_yakkety,
        build_on_ubuntu_zesty,
        build_on_ubuntu_artful,
        build_on_ubuntu_bionic,
        build_on_ubuntu_cosmic,
        build_on_ubuntu_disco,
        build_on_ubuntu_eoan,
        build_on_ubuntu_focal,
        build_on_ubuntu_groovy,
        build_on_ubuntu_hirsute,
        build_on_ubuntu_impish,
        build_on_ubuntu_jammy
      ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          path: ./artifact
      - run: bash .github/workflows/scripts/upload_to_repo.sh
