name: Publish binary package
on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
jobs:
  container-job:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:16.04
    steps:
      - uses: actions/checkout@v3
      - run: cat /etc/lsb-release
      - run: pwd
      - run: ls -hal

